- name: add ssh key for jeshish
  authorized_key:
    user: jeshish
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBln2l1MOcCK6tcUvdEcaGvMazkt+jDpJWoOGEUnJXIj ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
